import { withPayload } from "@payloadcms/next/withPayload";

/** @type {import('next').NextConfig} */
const nextConfig = {
  typescript: { ignoreBuildErrors: true },      // żeby build przeszedł mimo TS
  eslint: { ignoreDuringBuilds: true },         // opcjonalnie
  output: "standalone",                         // wymagane przez Twój Dockerfile

  webpack: (webpackConfig, { dev }) => {
    webpackConfig.resolve.extensionAlias = {
      ".cjs": [".cts", ".cjs"],
      ".js": [".ts", ".tsx", ".js", ".jsx"],
      ".mjs": [".mts", ".mjs"],
    };

    // cssnano-simple bundled with Next.js 15.4.10 crashes on `hsl(var(--x) / alpha)`
    // syntax generated by Tailwind alpha modifiers (bg-muted/30 etc.).
    // Constructor name is mangled in the bundle, so we identify the CSS minimizer
    // by its options.test regex which always matches .css files (not mangled).
    if (!dev) {
      webpackConfig.optimization.minimizer = webpackConfig.optimization.minimizer.filter(
        (plugin) => {
          const test = plugin.options?.test;
          return !(test instanceof RegExp && /css/i.test(test.source));
        },
      );
    }

    return webpackConfig;
  },
};

export default withPayload(nextConfig, { devBundleServerPackages: false });
