import { withPayload } from "@payloadcms/next/withPayload";

/** @type {import('next').NextConfig} */
const nextConfig = {
  typescript: { ignoreBuildErrors: true },      // żeby build przeszedł mimo TS
  eslint: { ignoreDuringBuilds: true },         // opcjonalnie
  output: "standalone",                         // wymagane przez Twój Dockerfile

  webpack: (webpackConfig, { dev }) => {
    webpackConfig.resolve.extensionAlias = {
      ".cjs": [".cts", ".cjs"],
      ".js": [".ts", ".tsx", ".js", ".jsx"],
      ".mjs": [".mts", ".mjs"],
    };

    // cssnano-simple bundled with Next.js 15.4.10 crashes on `hsl(var(--x) / alpha)`
    // syntax generated by Tailwind alpha modifiers (bg-muted/30 etc.)
    if (!dev) {
      webpackConfig.optimization.minimizer = webpackConfig.optimization.minimizer.filter(
        (plugin) => plugin.constructor?.name !== "CssMinimizerPlugin",
      );
    }

    return webpackConfig;
  },
};

export default withPayload(nextConfig, { devBundleServerPackages: false });
