/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    reservations: Reservation;
    payments: Payment;
    blackouts: Blackout;
    'occasional-inquiries': OccasionalInquiry;
    'menu-categories': MenuCategory;
    'menu-items': MenuItem;
    events: Event;
    media: Media;
    resources: Resource;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    blackouts: BlackoutsSelect<false> | BlackoutsSelect<true>;
    'occasional-inquiries': OccasionalInquiriesSelect<false> | OccasionalInquiriesSelect<true>;
    'menu-categories': MenuCategoriesSelect<false> | MenuCategoriesSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'dish-of-day': DishOfDay;
    'reservation-settings': ReservationSetting;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'dish-of-day': DishOfDaySelect<false> | DishOfDaySelect<true>;
    'reservation-settings': ReservationSettingsSelect<false> | ReservationSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: number;
  type: 'stolik' | 'kregle' | 'bilard' | 'impreza' | 'biznes';
  customer: {
    firstName: string;
    lastName: string;
    phone: string;
    email?: string | null;
  };
  notes?: string | null;
  day: string;
  allDay?: boolean | null;
  startHour?:
    | (
        | '0'
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
      )
    | null;
  startMinute?: ('0' | '15' | '30' | '45') | null;
  endHour?:
    | (
        | '0'
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
      )
    | null;
  endMinute?: ('0' | '15' | '30' | '45') | null;
  startsAt: string;
  endsAt?: string | null;
  partySize?: number | null;
  tablesCount?: number | null;
  resources?: (number | Resource)[] | null;
  /**
   * Szczegóły czasowe per zasób — generowane automatycznie przy rezerwacji online
   */
  segments?:
    | {
        resource?: (number | null) | Resource;
        startHour?: number | null;
        startMinute?: number | null;
        endHour?: number | null;
        endMinute?: number | null;
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  event?: (number | null) | Event;
  disabledPerson?: boolean | null;
  disabilityDetails?: string | null;
  invoice?: {
    wantInvoice?: boolean | null;
    invoiceType?: ('personal' | 'company') | null;
    nip?: string | null;
  };
  acceptRules: boolean;
  source: 'online' | 'phone' | 'staff';
  status: 'new' | 'confirmed' | 'cancelled' | 'no_show' | 'completed';
  depositRequired?: boolean | null;
  depositAmount?: number | null;
  paymentStatus?: ('not_required' | 'pending' | 'paid' | 'failed' | 'refunded' | 'forfeited') | null;
  paymentProvider?: 'p24' | null;
  payment?: (number | null) | Payment;
  groupId?: string | null;
  reservationNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  type: 'lane' | 'billiard';
  number: number;
  label: string;
  active?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  description?: string | null;
  kind?: ('impreza' | 'biznes') | null;
  /**
   * Dla darmowych wydarzeń ustaw 0.
   */
  pricePLN?: number | null;
  status: 'planned' | 'cancelled';
  day: string;
  startHour:
    | '0'
    | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | '10'
    | '11'
    | '12'
    | '13'
    | '14'
    | '15'
    | '16'
    | '17'
    | '18'
    | '19'
    | '20'
    | '21'
    | '22'
    | '23';
  startMinute: '0' | '15' | '30' | '45';
  endHour?:
    | (
        | '0'
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
      )
    | null;
  endMinute?: ('0' | '15' | '30' | '45') | null;
  startsAt: string;
  endsAt?: string | null;
  showOnHomepage?: boolean | null;
  blocksVenue?: boolean | null;
  blockAllDay?: boolean | null;
  image?: (number | null) | Media;
  capacity?: number | null;
  registrationsEnabled?: boolean | null;
  published?: boolean | null;
  takenSeats?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  provider: 'p24';
  status: 'pending' | 'paid' | 'failed' | 'refunded';
  amount: number;
  currency?: string | null;
  p24SessionId?: string | null;
  p24OrderId?: string | null;
  p24Sign?: string | null;
  reservation?: (number | null) | Reservation;
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blackouts".
 */
export interface Blackout {
  id: number;
  title: string;
  service: 'bowling' | 'billiard';
  day: string;
  allDay?: boolean | null;
  startHour?:
    | (
        | '0'
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
      )
    | null;
  startMinute?: ('0' | '15' | '30' | '45') | null;
  endHour?:
    | (
        | '0'
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
      )
    | null;
  endMinute?: ('0' | '15' | '30' | '45') | null;
  resources?: (number | Resource)[] | null;
  reason?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasional-inquiries".
 */
export interface OccasionalInquiry {
  id: number;
  type: 'komunia' | 'stypa' | 'urodziny' | 'inne';
  date: string;
  allDay?: boolean | null;
  startHour?:
    | (
        | '0'
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
      )
    | null;
  startMinute?: ('0' | '15' | '30' | '45') | null;
  endHour?:
    | (
        | '0'
        | '1'
        | '2'
        | '3'
        | '4'
        | '5'
        | '6'
        | '7'
        | '8'
        | '9'
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
      )
    | null;
  endMinute?: ('0' | '15' | '30' | '45') | null;
  startsAt?: string | null;
  endsAt?: string | null;
  people?: number | null;
  name: string;
  phone: string;
  email?: string | null;
  notes?: string | null;
  status: 'new' | 'in_progress' | 'confirmed' | 'rejected';
  payment?: {
    paid?: boolean | null;
    depositAmount?: number | null;
    depositPaid?: boolean | null;
    totalAmount?: number | null;
    totalPaid?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories".
 */
export interface MenuCategory {
  id: number;
  name: string;
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  name: string;
  description?: string | null;
  image?: (number | null) | Media;
  category: number | MenuCategory;
  price: number;
  promo?: {
    enabled?: boolean | null;
    promoPrice?: number | null;
    startsAt?: string | null;
    endsAt?: string | null;
  };
  order?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'staff';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'reservations';
        value: number | Reservation;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'blackouts';
        value: number | Blackout;
      } | null)
    | ({
        relationTo: 'occasional-inquiries';
        value: number | OccasionalInquiry;
      } | null)
    | ({
        relationTo: 'menu-categories';
        value: number | MenuCategory;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  type?: T;
  customer?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        phone?: T;
        email?: T;
      };
  notes?: T;
  day?: T;
  allDay?: T;
  startHour?: T;
  startMinute?: T;
  endHour?: T;
  endMinute?: T;
  startsAt?: T;
  endsAt?: T;
  partySize?: T;
  tablesCount?: T;
  resources?: T;
  segments?:
    | T
    | {
        resource?: T;
        startHour?: T;
        startMinute?: T;
        endHour?: T;
        endMinute?: T;
        price?: T;
        id?: T;
      };
  event?: T;
  disabledPerson?: T;
  disabilityDetails?: T;
  invoice?:
    | T
    | {
        wantInvoice?: T;
        invoiceType?: T;
        nip?: T;
      };
  acceptRules?: T;
  source?: T;
  status?: T;
  depositRequired?: T;
  depositAmount?: T;
  paymentStatus?: T;
  paymentProvider?: T;
  payment?: T;
  groupId?: T;
  reservationNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  provider?: T;
  status?: T;
  amount?: T;
  currency?: T;
  p24SessionId?: T;
  p24OrderId?: T;
  p24Sign?: T;
  reservation?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blackouts_select".
 */
export interface BlackoutsSelect<T extends boolean = true> {
  title?: T;
  service?: T;
  day?: T;
  allDay?: T;
  startHour?: T;
  startMinute?: T;
  endHour?: T;
  endMinute?: T;
  resources?: T;
  reason?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasional-inquiries_select".
 */
export interface OccasionalInquiriesSelect<T extends boolean = true> {
  type?: T;
  date?: T;
  allDay?: T;
  startHour?: T;
  startMinute?: T;
  endHour?: T;
  endMinute?: T;
  startsAt?: T;
  endsAt?: T;
  people?: T;
  name?: T;
  phone?: T;
  email?: T;
  notes?: T;
  status?: T;
  payment?:
    | T
    | {
        paid?: T;
        depositAmount?: T;
        depositPaid?: T;
        totalAmount?: T;
        totalPaid?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories_select".
 */
export interface MenuCategoriesSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  image?: T;
  category?: T;
  price?: T;
  promo?:
    | T
    | {
        enabled?: T;
        promoPrice?: T;
        startsAt?: T;
        endsAt?: T;
      };
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  kind?: T;
  pricePLN?: T;
  status?: T;
  day?: T;
  startHour?: T;
  startMinute?: T;
  endHour?: T;
  endMinute?: T;
  startsAt?: T;
  endsAt?: T;
  showOnHomepage?: T;
  blocksVenue?: T;
  blockAllDay?: T;
  image?: T;
  capacity?: T;
  registrationsEnabled?: T;
  published?: T;
  takenSeats?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  type?: T;
  number?: T;
  label?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dish-of-day".
 */
export interface DishOfDay {
  id: number;
  item?: (number | null) | MenuItem;
  customTitle?: string | null;
  customDescription?: string | null;
  validUntil?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservation-settings".
 */
export interface ReservationSetting {
  id: number;
  tables: {
    enabled?: boolean | null;
    disabledMessage?: string | null;
    availableTablesCount: number;
    arrivalWindowBeforeMinutes?: number | null;
    arrivalWindowAfterMinutes?: number | null;
    depositAmount?: number | null;
    reservationStartAfterOpeningMinutes?: number | null;
    latestReservationStartBeforeClosingMinutes?: number | null;
  };
  billiard: {
    enabled?: boolean | null;
    disabledMessage?: string | null;
    pricePerHour: number;
    reservationStartAfterOpeningMinutes?: number | null;
    latestReservationStartBeforeClosingMinutes?: number | null;
  };
  bowling: {
    enabled?: boolean | null;
    disabledMessage?: string | null;
    pricePerHour: number;
    reservationStartAfterOpeningMinutes?: number | null;
    latestReservationStartBeforeClosingMinutes?: number | null;
  };
  regulationsPdf?: (number | null) | Media;
  privacyPolicyPdf?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  slogan?: string | null;
  description?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  nip?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  openingHours?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dish-of-day_select".
 */
export interface DishOfDaySelect<T extends boolean = true> {
  item?: T;
  customTitle?: T;
  customDescription?: T;
  validUntil?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservation-settings_select".
 */
export interface ReservationSettingsSelect<T extends boolean = true> {
  tables?:
    | T
    | {
        enabled?: T;
        disabledMessage?: T;
        availableTablesCount?: T;
        arrivalWindowBeforeMinutes?: T;
        arrivalWindowAfterMinutes?: T;
        depositAmount?: T;
        reservationStartAfterOpeningMinutes?: T;
        latestReservationStartBeforeClosingMinutes?: T;
      };
  billiard?:
    | T
    | {
        enabled?: T;
        disabledMessage?: T;
        pricePerHour?: T;
        reservationStartAfterOpeningMinutes?: T;
        latestReservationStartBeforeClosingMinutes?: T;
      };
  bowling?:
    | T
    | {
        enabled?: T;
        disabledMessage?: T;
        pricePerHour?: T;
        reservationStartAfterOpeningMinutes?: T;
        latestReservationStartBeforeClosingMinutes?: T;
      };
  regulationsPdf?: T;
  privacyPolicyPdf?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  slogan?: T;
  description?: T;
  phone?: T;
  email?: T;
  address?: T;
  nip?: T;
  facebook?: T;
  instagram?: T;
  openingHours?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}